name: my-shop
on:
  push:
    branches: [ "master" ]

      
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps: npm install, build, and test
      - uses: actions/checkout!v1
      - run: npm install
      - run: npm run build --if-present
      - run: npm run test --if-present
    